# Generated by Django 3.2.13 on 2023-09-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ThingsILike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('when', models.CharField(max_length=30)),
                ('what', models.CharField(max_length=30)),
                ('how_often', models.CharField(choices=[('N', 'Not Often'), ('S', 'Some Times'), ('A', 'Always')], max_length=1)),
            ],
        ),
    ]
